#!/usr/bin/env bash

# undervolt
pip3 install undervolt
python3 -m undervolt --gpu -125 --core -125 --cache -125

# undervolt on boot
echo '[Unit]\nDescription=undervolt\n[Service]\nType=oneshot\nExecStart=python3 -m undervolt -v --core -125 --cache -125 --gpu -125' > /etc/systemd/system/undervolt.service
